from __future__ import annotations

from typing import Any


LAYER_STYLES: dict[str, dict[str, Any]] = {
    "sar_before": {
        "display_name": "Imagine de referinta SAR (BEFORE)",
        "vis_params": {"min": -25, "max": 0, "palette": ["111827", "e5e7eb"]},
        "legend_color": "#94a3b8",
        "description": "Scena sau compozit SAR BEFORE in tonuri gri.",
        "category": "Analiza apei prin SAR",
        "legend_items": [("#94a3b8", "semnal radar in tonuri gri")],
        "source": "COPERNICUS/S1_GRD",
        "date_or_period": "perioada BEFORE",
        "layer_type": "BEFORE",
    },
    "sar_after": {
        "display_name": "Imagine dupa eveniment SAR (AFTER)",
        "vis_params": {"min": -25, "max": 0, "palette": ["111827", "e5e7eb"]},
        "legend_color": "#64748b",
        "description": "Scena sau compozit SAR AFTER in tonuri gri.",
        "category": "Analiza apei prin SAR",
        "legend_items": [("#64748b", "semnal radar in tonuri gri")],
        "source": "COPERNICUS/S1_GRD",
        "date_or_period": "perioada AFTER",
        "layer_type": "AFTER",
    },
    "sar_difference": {
        "display_name": "Diferenta SAR",
        "vis_params": {"bands": ["sar_difference"], "min": -5, "max": 5, "palette": ["2563eb", "f8fafc", "dc2626"]},
        "legend_color": "#dc2626",
        "description": "Diferenta observata intre imaginile SAR BEFORE si AFTER.",
        "category": "Layere SAR optionale",
        "legend_items": [("#2563eb", "scadere semnal"), ("#dc2626", "crestere semnal")],
        "source": "COPERNICUS/S1_GRD",
        "date_or_period": "BEFORE -> AFTER",
        "layer_type": "DELTA",
    },
    "sar_ratio": {
        "display_name": "Raport SAR",
        "vis_params": {"bands": ["sar_ratio"], "min": 0.8, "max": 2.0, "palette": ["2563eb", "facc15", "dc2626"]},
        "legend_color": "#facc15",
        "description": "Raport SAR pentru change detection.",
        "category": "Layere SAR optionale",
        "legend_items": [("#2563eb", "raport redus"), ("#facc15", "tranzitie"), ("#dc2626", "raport ridicat")],
        "source": "COPERNICUS/S1_GRD",
        "date_or_period": "BEFORE -> AFTER",
        "layer_type": "DELTA",
    },
    "sar_water_before": {
        "display_name": "Apa observata prin SAR inainte de eveniment",
        "vis_params": {"palette": ["7dd3fc"]},
        "legend_color": "#7dd3fc",
        "description": "Pixeli SAR compatibili cu apa in scena BEFORE.",
        "category": "Analiza apei prin SAR",
        "legend_items": [("#7dd3fc", "apa observata prin SAR in BEFORE")],
        "source": "COPERNICUS/S1_GRD",
        "date_or_period": "perioada BEFORE",
        "layer_type": "BEFORE",
    },
    "sar_water_after": {
        "display_name": "Apa observata prin SAR dupa eveniment",
        "vis_params": {"palette": ["2563eb"]},
        "legend_color": "#2563eb",
        "description": "Pixeli SAR compatibili cu apa in scena AFTER.",
        "category": "Analiza apei prin SAR",
        "legend_items": [("#2563eb", "apa observata prin SAR in AFTER")],
        "source": "COPERNICUS/S1_GRD",
        "date_or_period": "perioada AFTER",
        "layer_type": "AFTER",
    },
    "sar_new_water": {
        "display_name": "Apa noua evidentiata prin SAR",
        "vis_params": {"palette": ["22d3ee"]},
        "legend_color": "#22d3ee",
        "description": "Apa observata automat prin SAR in AFTER, absenta in BEFORE.",
        "category": "Analiza apei prin SAR",
        "legend_items": [("#22d3ee", "apa observata in AFTER, absenta in BEFORE")],
        "source": "COPERNICUS/S1_GRD",
        "date_or_period": "BEFORE -> AFTER",
        "layer_type": "REZULTAT",
    },
    "sar_persistent_water": {
        "display_name": "Apa persistenta observata prin SAR",
        "vis_params": {"palette": ["1e3a8a"]},
        "legend_color": "#1e3a8a",
        "description": "Apa observata automat prin SAR in ambele scene.",
        "category": "Layere SAR optionale",
        "legend_items": [("#1e3a8a", "apa observata in BEFORE si AFTER")],
        "source": "COPERNICUS/S1_GRD",
        "date_or_period": "BEFORE -> AFTER",
        "layer_type": "REZULTAT",
    },
    "sar_water_loss": {
        "display_name": "Pierdere de apa observata prin SAR",
        "vis_params": {"palette": ["f97316"]},
        "legend_color": "#f97316",
        "description": "Apa observata automat prin SAR in BEFORE, absenta in AFTER.",
        "category": "Layere SAR optionale",
        "legend_items": [("#f97316", "apa prezenta in BEFORE, absenta in AFTER")],
        "source": "COPERNICUS/S1_GRD",
        "date_or_period": "BEFORE -> AFTER",
        "layer_type": "DELTA",
    },
    "flood_extent": {
        "display_name": "Extindere preliminara filtrata",
        "vis_params": {"palette": ["be185d"]},
        "legend_color": "#be185d",
        "description": "Extindere preliminara SAR filtrata prin change detection si filtre auxiliare.",
        "category": "Analiza apei prin SAR",
        "legend_items": [("#be185d", "extindere preliminara SAR filtrata")],
        "source": "COPERNICUS/S1_GRD",
        "date_or_period": "BEFORE -> AFTER",
        "layer_type": "REZULTAT",
    },
    "dynamic_world_before": {
        "display_name": "Dynamic World inainte de eveniment",
        "vis_params": {
            "min": 0,
            "max": 8,
            "palette": ["419bdf", "397d49", "88b053", "7a87c6", "e49635", "dfc35a", "c4281b", "a59b8f", "b39fe1"],
        },
        "legend_color": "#419bdf",
        "description": "Clasa modala Dynamic World BEFORE.",
        "category": "Dynamic World",
        "legend_items": [
            ("#419bdf", "apa"),
            ("#397d49", "arbori"),
            ("#88b053", "iarba"),
            ("#7a87c6", "vegetatie inundata"),
            ("#e49635", "teren agricol"),
            ("#dfc35a", "arbusti"),
            ("#c4281b", "construit"),
            ("#a59b8f", "sol nud"),
            ("#b39fe1", "zapada/gheata"),
        ],
        "source": "GOOGLE/DYNAMICWORLD/V1",
        "date_or_period": "perioada BEFORE",
        "layer_type": "BEFORE",
    },
    "dynamic_world_after": {
        "display_name": "Dynamic World dupa eveniment",
        "vis_params": {
            "min": 0,
            "max": 8,
            "palette": ["419bdf", "397d49", "88b053", "7a87c6", "e49635", "dfc35a", "c4281b", "a59b8f", "b39fe1"],
        },
        "legend_color": "#397d49",
        "description": "Clasa modala Dynamic World AFTER.",
        "category": "Dynamic World",
        "legend_items": [
            ("#419bdf", "apa"),
            ("#397d49", "arbori"),
            ("#88b053", "iarba"),
            ("#7a87c6", "vegetatie inundata"),
            ("#e49635", "teren agricol"),
            ("#dfc35a", "arbusti"),
            ("#c4281b", "construit"),
            ("#a59b8f", "sol nud"),
            ("#b39fe1", "zapada/gheata"),
        ],
        "source": "GOOGLE/DYNAMICWORLD/V1",
        "date_or_period": "perioada AFTER",
        "layer_type": "AFTER",
    },
    "dynamic_world_changes": {
        "display_name": "Diferente observate Dynamic World",
        "vis_params": {"min": 1, "max": 4, "palette": ["e5e7eb", "facc15", "fb7185", "0284c7"]},
        "legend_color": "#a78bfa",
        "description": "Diferente observate Dynamic World intre BEFORE si AFTER.",
        "category": "Dynamic World",
        "legend_items": [("#0284c7", "apa noua"), ("#f59e0b", "pierdere apa"), ("#a78bfa", "alte diferente"), ("transparent", "fara schimbare")],
        "source": "GOOGLE/DYNAMICWORLD/V1",
        "date_or_period": "BEFORE -> AFTER",
        "layer_type": "DELTA",
    },
    "dynamic_world_new_water": {
        "display_name": "Apa noua Dynamic World",
        "vis_params": {"palette": ["818cf8"]},
        "legend_color": "#818cf8",
        "description": "Diferente observate Dynamic World: non-apa BEFORE reclasificata ca apa AFTER.",
        "category": "Dynamic World",
        "legend_items": [("#818cf8", "pixeli reclasificati ca apa dupa eveniment")],
        "source": "GOOGLE/DYNAMICWORLD/V1",
        "date_or_period": "BEFORE -> AFTER",
        "layer_type": "REZULTAT",
    },
    "dynamic_world_water_loss": {
        "display_name": "Pierdere apa Dynamic World",
        "vis_params": {"palette": ["f59e0b"]},
        "legend_color": "#f59e0b",
        "description": "Diferente observate Dynamic World: apa BEFORE reclasificata non-apa AFTER.",
        "category": "Dynamic World",
        "legend_items": [("#f59e0b", "apa BEFORE reclasificata non-apa AFTER")],
        "source": "GOOGLE/DYNAMICWORLD/V1",
        "date_or_period": "BEFORE -> AFTER",
        "layer_type": "DELTA",
    },
    "dynamic_world_other_change": {
        "display_name": "Alte diferente Dynamic World",
        "vis_params": {"palette": ["a78bfa"]},
        "legend_color": "#a78bfa",
        "description": "Alte diferente observate Dynamic World.",
        "category": "Dynamic World",
        "legend_items": [("#a78bfa", "alte diferente observate")],
        "source": "GOOGLE/DYNAMICWORLD/V1",
        "date_or_period": "BEFORE -> AFTER",
        "layer_type": "DELTA",
    },
    "sar_dynamic_world_new_water_overlap": {
        "display_name": "Suprapunere SAR x Dynamic World",
        "vis_params": {"palette": ["16a34a"]},
        "legend_color": "#16a34a",
        "description": "Apa noua observata atat prin SAR, cat si prin Dynamic World.",
        "category": "Corelare SAR x Dynamic World",
        "legend_items": [("#16a34a", "apa noua identificata de ambele metode")],
        "source": "COPERNICUS/S1_GRD + GOOGLE/DYNAMICWORLD/V1",
        "date_or_period": "BEFORE -> AFTER",
        "layer_type": "REZULTAT COMBINAT",
    },
    "new_water_only_sar": {
        "display_name": "Apa noua identificata doar prin SAR",
        "vis_params": {"palette": ["67e8f9"]},
        "legend_color": "#67e8f9",
        "description": "Apa noua observata prin SAR fara corespondent Dynamic World.",
        "category": "Corelare SAR x Dynamic World",
        "legend_items": [("#67e8f9", "apa noua identificata doar prin SAR")],
        "source": "COPERNICUS/S1_GRD + GOOGLE/DYNAMICWORLD/V1",
        "date_or_period": "BEFORE -> AFTER",
        "layer_type": "REZULTAT COMBINAT",
    },
    "new_water_only_dynamic_world": {
        "display_name": "Apa noua identificata doar prin Dynamic World",
        "vis_params": {"palette": ["9333ea"]},
        "legend_color": "#9333ea",
        "description": "Apa noua Dynamic World fara corespondent SAR.",
        "category": "Corelare SAR x Dynamic World",
        "legend_items": [("#9333ea", "apa noua identificata doar prin Dynamic World")],
        "source": "COPERNICUS/S1_GRD + GOOGLE/DYNAMICWORLD/V1",
        "date_or_period": "BEFORE -> AFTER",
        "layer_type": "REZULTAT COMBINAT",
    },
    "osm_buildings": {
        "display_name": "Cladiri potential expuse OSM",
        "vis_params": {},
        "legend_color": "#ef4444",
        "description": "Cladiri OpenStreetMap intersectate cu extinderea preliminara sau bufferul operational.",
        "category": "Impact operational OSM",
        "legend_items": [
            ("#dc2626", "expunere ridicata"),
            ("#f97316", "expunere medie"),
            ("#facc15", "expunere redusa"),
        ],
        "source": "OpenStreetMap via Overpass API",
        "date_or_period": "interogare la rularea analizei",
        "layer_type": "VECTOR OSM",
    },
    "osm_roads": {
        "display_name": "Drumuri potential intersectate OSM",
        "vis_params": {},
        "legend_color": "#f97316",
        "description": "Drumuri OSM potential intersectate de extinderea preliminara sau de zona de proximitate.",
        "category": "Impact operational OSM",
        "legend_items": [
            ("#dc2626", "intersectie directa"),
            ("#f97316", "in buffer operational"),
            ("#facc15", "expunere redusa"),
        ],
        "source": "OpenStreetMap via Overpass API",
        "date_or_period": "interogare la rularea analizei",
        "layer_type": "VECTOR OSM",
    },
    "osm_critical": {
        "display_name": "Obiective critice potential expuse OSM",
        "vis_params": {},
        "legend_color": "#7c3aed",
        "description": "Spitale, servicii de interventie, scoli, farmacii si alte obiective critice OSM potential expuse.",
        "category": "Impact operational OSM",
        "legend_items": [
            ("#dc2626", "serviciu medical sau interventie"),
            ("#7c3aed", "obiectiv critic operational"),
            ("#f97316", "expunere medie"),
        ],
        "source": "OpenStreetMap via Overpass API",
        "date_or_period": "interogare la rularea analizei",
        "layer_type": "VECTOR OSM",
    },
    "osm_railways": {
        "display_name": "Cai ferate intersectate OSM",
        "vis_params": {},
        "legend_color": "#111827",
        "description": "Segmente feroviare OSM intersectate sau apropiate de extinderea preliminara.",
        "category": "Impact operational OSM",
        "legend_items": [
            ("#dc2626", "intersectie directa"),
            ("#111827", "cale ferata in zona analizata"),
        ],
        "source": "OpenStreetMap via Overpass API",
        "date_or_period": "interogare la rularea analizei",
        "layer_type": "VECTOR OSM",
    },
    "osm_bridges": {
        "display_name": "Poduri intersectate OSM",
        "vis_params": {},
        "legend_color": "#0ea5e9",
        "description": "Poduri OSM intersectate sau aflate in proximitatea extinderii preliminare.",
        "category": "Impact operational OSM",
        "legend_items": [
            ("#dc2626", "intersectie directa"),
            ("#0ea5e9", "pod in zona analizata"),
        ],
        "source": "OpenStreetMap via Overpass API",
        "date_or_period": "interogare la rularea analizei",
        "layer_type": "VECTOR OSM",
    },
}

LAYER_STYLES.update(
    {
        "land_cover_changes": {
            **LAYER_STYLES["dynamic_world_changes"],
            "display_name": "Diferente observate Dynamic World",
        },
        "intersected_land_cover": {
            **LAYER_STYLES["dynamic_world_after"],
            "display_name": "Dynamic World intersectat cu extinderea preliminara",
            "description": "Clase Dynamic World AFTER mascate cu extinderea preliminara filtrata.",
            "date_or_period": "perioada AFTER",
            "layer_type": "REZULTAT",
        },
        "rgb_before": {
            "display_name": "Imagine optica Sentinel-2 de referinta (BEFORE)",
            "vis_params": {"min": 0, "max": 3000, "bands": ["B4", "B3", "B2"]},
            "legend_color": "#22c55e",
            "description": "Compozit optic Sentinel-2 RGB pentru perioada BEFORE.",
            "category": "Layere optice optionale",
            "legend_items": [("#22c55e", "RGB culoare naturala")],
            "source": "COPERNICUS/S2_SR_HARMONIZED",
            "date_or_period": "perioada BEFORE",
            "layer_type": "BEFORE",
        },
        "rgb_after": {
            "display_name": "Imagine optica Sentinel-2 dupa eveniment (AFTER)",
            "vis_params": {"min": 0, "max": 3000, "bands": ["B4", "B3", "B2"]},
            "legend_color": "#16a34a",
            "description": "Compozit optic Sentinel-2 RGB pentru perioada AFTER.",
            "category": "Layere optice optionale",
            "legend_items": [("#16a34a", "RGB culoare naturala")],
            "source": "COPERNICUS/S2_SR_HARMONIZED",
            "date_or_period": "perioada AFTER",
            "layer_type": "AFTER",
        },
    }
)

for _index_id, _label in {
    "ndwi_before": "NDWI de referinta (BEFORE)",
    "ndwi_after": "NDWI dupa eveniment (AFTER)",
    "delta_ndwi": "Diferenta NDWI",
    "mndwi_before": "MNDWI de referinta (BEFORE)",
    "mndwi_after": "MNDWI dupa eveniment (AFTER)",
    "delta_mndwi": "Diferenta MNDWI",
    "ndvi_before": "NDVI de referinta (BEFORE)",
    "ndvi_after": "NDVI dupa eveniment (AFTER)",
    "delta_ndvi": "Diferenta NDVI",
    "ndmi_before": "NDMI de referinta (BEFORE)",
    "ndmi_after": "NDMI dupa eveniment (AFTER)",
    "delta_ndmi": "Diferenta NDMI",
}.items():
    LAYER_STYLES[_index_id] = {
        "display_name": _label,
        "vis_params": {"min": -1, "max": 1, "palette": ["8b5cf6", "f8fafc", "0284c7"]},
        "legend_color": "#0284c7",
        "description": "Indice optic Sentinel-2 pentru context vizual optional.",
        "category": "Layere optice optionale",
        "legend_items": [("#8b5cf6", "valoare redusa"), ("#0284c7", "valoare ridicata")],
        "source": "COPERNICUS/S2_SR_HARMONIZED",
        "date_or_period": "perioada BEFORE/AFTER",
        "layer_type": "INDICE OPTIC",
    }


def _style_with_defaults(layer_id: str, style: dict[str, Any]) -> dict[str, Any]:
    display_name = style.get("display_name", layer_id)
    return {
        "display_name": display_name,
        "category": style.get("category", "Alte layere"),
        "vis_params": style.get("vis_params", {}),
        "legend_color": style.get("legend_color", "#94a3b8"),
        "legend_items": style.get("legend_items") or [(style.get("legend_color", "#94a3b8"), display_name)],
        "description": style.get("description", ""),
        "source": style.get("source", "sursa nespecificata"),
        "date_or_period": style.get("date_or_period", "data/perioada indisponibila"),
        "layer_type": style.get("layer_type", "LAYER"),
    }


def layer_style(layer_id: str) -> dict[str, Any]:
    style = LAYER_STYLES.get(layer_id, {})
    return _style_with_defaults(layer_id, style) if style else {}


def vis_params_by_display_name() -> dict[str, dict[str, Any]]:
    return {
        str(style["display_name"]): dict(style.get("vis_params") or {})
        for style in LAYER_STYLES.values()
        if style.get("display_name")
    }
